
services:
  vue-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8083:8083"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=${VUE_APP_API_URL:-http://localhost:8080/api}
    volumes:
      - ./nginx-logs:/var/log/nginx