
services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vue-frontend-dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8083:8083"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
      - NODE_ENV=development
      - VUE_APP_API_URL=${VUE_APP_API_URL:-http://localhost:8080/api}
    networks:
      - app-network
    command: npm run serve

networks:
  app-network:
    driver: bridge